import React from 'react';
import Link from 'next/link';
import { FileCheck, ArrowLeft, BookOpen, AlertTriangle } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service | IELTS Mentor AI',
  description: 'Terms of Service and conditions of use for IELTS Mentor AI Writing Platform.',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-gray-950 text-slate-900 dark:text-slate-100 transition-colors">
      {/* Header */}
      <header className="border-b border-slate-200 dark:border-gray-800 bg-white dark:bg-gray-900/90 sticky top-0 z-20 backdrop-blur-md">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 text-xs font-semibold text-slate-600 dark:text-gray-300 hover:text-brand-600 dark:hover:text-brand-400 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to IELTS Mentor AI</span>
          </Link>
          <div className="flex items-center gap-2">
            <FileCheck className="h-5 w-5 text-brand-600 dark:text-brand-400" />
            <span className="font-bold text-sm text-slate-900 dark:text-white">Terms of Service</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-black tracking-tight text-slate-900 dark:text-white">
            Terms of Service & Acceptable Use
          </h1>
          <p className="text-xs text-slate-500 dark:text-gray-400 mt-2">
            Last Updated: October 7, 2026 • Effective Date: October 7, 2026
          </p>
        </div>

        {/* Acceptance */}
        <div className="p-6 rounded-2xl bg-white dark:bg-gray-900 border border-slate-200 dark:border-gray-800 shadow-sm space-y-3 leading-relaxed text-sm">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <BookOpen className="h-4 w-4 text-brand-600 dark:text-brand-400" />
            <span>1. Acceptance of Terms</span>
          </h2>
          <p className="text-slate-600 dark:text-gray-300">
            By creating an account, accessing, or using <strong>IELTS Mentor AI</strong> (&ldquo;the Service&rdquo;) available at{' '}
            <a href="https://writing-platform-two.vercel.app" className="text-brand-600 dark:text-brand-400 underline">
              https://writing-platform-two.vercel.app
            </a>,
            you agree to be bound by these Terms of Service. If you do not agree, you must discontinue using the platform immediately.
          </p>
        </div>

        {/* Educational Purpose & Disclaimer */}
        <div className="p-6 rounded-2xl bg-amber-50/70 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900/60 shadow-sm space-y-3 leading-relaxed text-sm">
          <h2 className="text-lg font-bold text-amber-950 dark:text-amber-100 flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400" />
            <span>2. Educational Disclaimer & Third-Party Trademark Notice</span>
          </h2>
          <p className="text-slate-700 dark:text-gray-200 text-xs">
            <strong>IELTS®</strong> is a registered trademark of the University of Cambridge ESOL, the British Council, and IDP Education Australia.
            IELTS Mentor AI is an independent educational preparatory tool. This platform is not affiliated with, endorsed by, or approved by the University of Cambridge, the British Council, or IDP.
          </p>
          <p className="text-slate-700 dark:text-gray-200 text-xs">
            Band scores and examiner feedback generated by the platform are pedagogical estimates designed to assist your preparation and do not guarantee an official exam result.
          </p>
        </div>

        {/* User Accounts */}
        <div className="p-6 rounded-2xl bg-white dark:bg-gray-900 border border-slate-200 dark:border-gray-800 shadow-sm space-y-3 leading-relaxed text-sm">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">3. User Accounts & Google Sign-In</h2>
          <p className="text-slate-600 dark:text-gray-300">
            When you register via email or authenticate using Google OAuth, you agree to provide accurate information and maintain the security of your credentials. You are responsible for all activities that occur under your account.
          </p>
        </div>

        {/* User Content & Intellectual Property */}
        <div className="p-6 rounded-2xl bg-white dark:bg-gray-900 border border-slate-200 dark:border-gray-800 shadow-sm space-y-3 leading-relaxed text-sm">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">4. User Content & Intellectual Property</h2>
          <p className="text-slate-600 dark:text-gray-300">
            You retain 100% ownership of all essays, texts, and writing samples you author and submit to the platform. By submitting content, you grant IELTS Mentor AI a limited license strictly to process, analyze, and generate AI feedback and scores on your behalf.
          </p>
        </div>

        {/* Prohibited Activities */}
        <div className="p-6 rounded-2xl bg-white dark:bg-gray-900 border border-slate-200 dark:border-gray-800 shadow-sm space-y-3 leading-relaxed text-sm">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">5. Prohibited Activities</h2>
          <ul className="list-disc pl-5 space-y-1 text-slate-600 dark:text-gray-300 text-xs">
            <li>Attempting to bypass security, rate limits, or reverse-engineer the API.</li>
            <li>Submitting malicious code, scripts, or abusive content.</li>
            <li>Sharing credentials or exploiting the service for automated scraping.</li>
          </ul>
        </div>

        {/* Contact */}
        <div className="p-6 rounded-2xl bg-slate-100 dark:bg-gray-900/60 border border-slate-200 dark:border-gray-800 text-xs text-slate-600 dark:text-gray-400 space-y-2">
          <h3 className="font-bold text-slate-900 dark:text-white text-sm">6. Contact Information</h3>
          <p>For questions or assistance regarding these terms:</p>
          <p className="font-mono">Email: support@ieltsmentor.ai</p>
          <p>Website: https://writing-platform-two.vercel.app</p>
        </div>
      </main>
    </div>
  );
}
